# -*- coding: utf-8 -*-
"""wordclouds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bdKsNt-dy1lq5dhfvA0WacSTEosMmgi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

df = pd.read_csv("data/processed.csv")
df.dropna(inplace=True)

X = df["Tweets"].values
y = df["Tag"].values

plt.figure(figsize=(20,10))
subset1 = df[df['Tag']==1]
text_gender = subset1.Tweets.values
cloud1=WordCloud(background_color='black',colormap="Dark2",collocations=False,width=2000,height=1000).generate(" ".join(text_gender))

plt.axis('off')
plt.title("Religion",fontsize=40)
plt.imshow(cloud1)

plt.figure(figsize=(20,10))
subset1 = df[df['Tag']==2]
text_gender = subset1.Tweets.values
cloud1=WordCloud(background_color='black',colormap="Dark2",collocations=False,width=2000,height=1000).generate(" ".join(text_gender))

plt.axis('off')
plt.title("Gender",fontsize=40)
plt.imshow(cloud1)

plt.figure(figsize=(20,10))
subset1 = df[df['Tag']==3]
text_gender = subset1.Tweets.values
cloud1=WordCloud(background_color='black',colormap="Dark2",collocations=False,width=2000,height=1000).generate(" ".join(text_gender))

plt.axis('off')
plt.title("Ethnicity",fontsize=40)
plt.imshow(cloud1)

plt.figure(figsize=(20,10))
subset1 = df[df['Tag']==4]
text_gender = subset1.Tweets.values
cloud1=WordCloud(background_color='black',colormap="Dark2",collocations=False,width=2000,height=1000).generate(" ".join(text_gender))

plt.axis('off')
plt.title("Age",fontsize=40)
plt.imshow(cloud1)